### PR TITLE
Add new function object to write differential stress

### PR DESCRIPTION
**Pull request by scottlevie97**

### CODE REVIEW

**Comment by scottlevie97** [comment]
The latest 3 commits allow for a boolean flag labelled **compressionPositive** when defining principal stresses or differential stresses in system/controlDict. 

Perhaps it would have been easier to have the differential stresses calculated within the principal stresses function objects?

**Comment by philipcardiff** [comment]
Thanks Scott, Yep, it is a good idea to merge the differential stress into the principal stress function object to avoid re-calculating the principal stresses.

**Comment by philipcardiff** [comment]
As you can see above, I just pushed two commits to make these changes. I will merge these once the tests finish and pass.

**Comment by philipcardiff** [comment]
@scottlevie97 : I added a `compressionPositive` flag just like for the differential and principal stresses.

Once the tests complete, I will merge it.

**Pull request merged**
