### PR TITLE
Added contribute section

### PR DESCRIPTION
**Pull request by iBatistic**
In issue https://github.com/solids4foam/solids4foam/pull/145, it was pointed out that the project was missing a "Contributing" section. I've drafted an initial version of it. @philipcardiff, feel free to modify it or remove it if you do not want to include it.

### CODE REVIEW

**Comment by iBatistic** [comment]
Hi @philipcardiff,  I made a small mess. Instead of using my fork, I accidentally created a new branch called iBatistic-patch-contribute.md based on the main branch. Besides, it looks like some of the content from #138 might be included in this PR as well. You can ignore that for now and only accept the text from the markdown file if you'd like.

**Comment by philipcardiff** [comment]
Thanks @iBatistic, this all looks good to me. I will merge it.

**Comment by philipcardiff** [comment]
Closed to avoid confusion. New merge request to be opened for merging the contributors file edits.

**Review by MakisH — COMMENTED** [review]
The new section already looks good. Note that the common convention would be to have such information in a [`CONTRIBUTING.md` file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) in the root of the repository, and the details on what to include in an issue or PR in an [issue/PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

**Comment by iBatistic** [comment]
> Closed to avoid confusion. New merge request to be opened for merging the contributors file edits.

Contribute section added in PR #152. Later on, we can improve it with additional info from the PR template if needed.

**Comment by philipcardiff** [comment]
> The new section already looks good. Note that the common convention would be to have such information in a [`CONTRIBUTING.md` file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) in the root of the repository, and the details on what to include in an issue or PR in an [issue/PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

I added a PR template in cb4814af and d44b5ce7.

**Pull request closed without merging**
