### PR TITLE
Updates to tutorial README.md files 

### PR DESCRIPTION
**Pull request by iBatistic**

### CODE REVIEW

**Comment by philipcardiff** [comment]
These tutorials are now online, e.g. https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/beamsPlatesShells/squarePlate.html and https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/linearElasticity/slidingFrictionBall.html.

For https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/linearElasticity/slidingFrictionBall.html, the link for the video is missing. @iBatistic do you have an animation file for this? You can upload it to YouTube and update the link (you need the characters from a certain point in the URL) or we can upload it to the official solids4foam YouTube channel (https://www.youtube.com/channel/UC0jo_22Hi29xHpcnv_b4Iag) which @cloner0110 runs or I can put it on my channel.

**Comment by iBatistic** [comment]
Hi @philipcardiff , yes, I have an animation, here is the link:

[slidingFrictionBall-animation.zip](https://github.com/solids4foam/solids4foam/files/13998825/slidingFrictionBall-animation.zip)

I think it would be better if it were uploaded to your or the solids4foam channel.

**Comment by cloner0110** [comment]
@iBatistic I can upload the animation on the YouTube channel; please tell me the caption and any other relevant information.

**Comment by iBatistic** [comment]
Hi @cloner0110 , great, thanks.  I guess the name should be:
Frictional sliding of an elastic cylinder segment.

For the description, we can put something like this:
solids4foam is an open-source finite volume toolbox for solid mechanics and fluid-solid interaction simulations. The simulation is available within the toolbox tutorials under the name slidingFrictionBall.

**Comment by cloner0110** [comment]
Sure, I will upload it. Is there any link needed for the video? e.g., linking to existing web pages on the website.

**Comment by iBatistic** [comment]
That is a good idea; we can put a link to the solids4foam  tutorial page where this case is documented:
https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/linearElasticity/slidingFrictionBall.html

**Comment by philipcardiff** [comment]
@cloner0110, as you are having some issues with the YouTube account, I have uploaded the video to mine. It is now online: https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/linearElasticity/slidingFrictionBall.html

Once the YouTube account is back working, we can add videos there (@cloner0110, you could give @iBatistic access if he wants it, too) and we can migrate videos if we like too.

Thanks!

**Comment by philipcardiff** [comment]
New video (on the solids4foam YouTube) is now online: https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/linearElasticity/slidingFrictionBall.html

**Pull request merged**
