### PR TITLE
Fix for getNumberOfProcessors() & removing compression specifier warning

### PR DESCRIPTION
**Pull request by iBatistic**
## Pull Request Description 🚀

Solution for annoying warning when not using fe41:
```
--> FOAM Warning : 
    From static Foam::IOstreamOption::compressionType Foam::IOstreamOption::compressionEnum(const Foam::word&, Foam::IOstreamOption::compressionType)
    in file db/options/IOstreamOption.C at line 171
    Unknown compression specifier 'uncompressed' using compression off
```
Fix for `function solids4Foam::getNumberOfProcessors()` and resolving @philipcardiff note in #138

---

## Related Issues and Discussions 🧩

- Note in #138.

---

## Changes Made 🛠️

- [x] **Bug Fix**: `getNumberOfProcessors()` was returning `numberOfSubdomains 2` instead of `2`. 
COM was able to work properly with this because of different `mpirun` version compared to fe41.

### Summary of Changes:
- **Files Modified**: controlDicts, Allrun scripts, solids4FoamScripts.sh

---

## Checklist ✅

Please ensure the following before submitting your PR:

- [x] Code compiles successfully with **OpenFOAM** or **foam-extend** versions (e.g., `v2312`, `4.1`).
- [x] I tested the changes with the provided tutorial or relevant test cases.
- [x] Added relevant **comments** or **documentation** for clarity.
- [x] The PR passes existing **GitHub Actions CI checks** (e.g., build and test).
- [x] Code follows the project's **coding style** and conventions.

---

### CODE REVIEW

**Comment by iBatistic** [comment]
With this PR, I have added a solution for #150 (commits eef0212, 69effeb, 1b53983).

**Comment by philipcardiff** [comment]
> With this PR, I have added a solution for #150 (commits [eef0212](https://github.com/solids4foam/solids4foam/commit/eef02120d96ca7875002131cc93e18c32c668351), [69effeb](https://github.com/solids4foam/solids4foam/commit/69effeb93adaff838f28e69a92d7df52a26943d5), [1b53983](https://github.com/solids4foam/solids4foam/commit/1b539835162982b764b78b967fdd23ea551a371d)).

@iBatistic : I think you need to open a new pull request from your branch to merge these latest changes, as this pull request was already merged before you made these changes.

**Comment by iBatistic** [comment]
> @iBatistic : I think you need to open a new pull request from your branch to merge these latest changes, as this pull request was already merged before you made these changes.

@philipcardiff, as far as I can tell, the changes in the mentioned commits were merged into the development branch when this PR was closed. You can double-check, but I believe a new PR is not needed for those commits.

**Comment by philipcardiff** [comment]
OK, now I see the issue:
- [eef0212](https://github.com/solids4foam/solids4foam/commit/eef02120d96ca7875002131cc93e18c32c668351) update the `README.md` to correctly explain how to call the `Allrun` script, e.g. `./Allrun sonicLiquidFluid`
- But https://github.com/solids4foam/solids4foam/commit/69effeb93adaff838f28e69a92d7df52a26943d5 seems to have reverted these changes

Here is the latest development branch for the 3dTube `README.md`: https://github.com/solids4foam/solids4foam/blob/development/tutorials/fluidSolidInteraction/3dTube/README.md
where you can see that the `README.md` contains the old instructions.

OK, I manually copied your changes from https://github.com/solids4foam/solids4foam/commit/eef02120d96ca7875002131cc93e18c32c668351 and pushed them to the development branch in b3c297e1; I set you as the author of the commit.

I think this is all resolved now.

**Pull request merged**
