### PR TITLE
Update for layeredPipe tutorial case

### PR DESCRIPTION
**Pull request by iBatistic**
- Sigma field is transformed to the cylindrical coordinate system using the `fieldCoordinateSystemTransform` function object
- In `sample` and `sampleDict`, one line used to extract the sigma field instead of two.
- The analytical solution is incorporated into the `plot.gnuplot` script
- The `README.md` file is added.

### CODE REVIEW

**Comment by iBatistic** [comment]
Hmm, the build on ORG failed because I naively thought that ORG had the same function object as COM. In the ORG, the function object should look like this:
```
   cartesianToCylindrical
    {
        type        cylindrical;
        libs        ("libfieldFunctionObjects.so");

        origin      (0 0 0);
        axis        (0 0 1);

        field       sigma;
    }
```

Anyway, this is not the only reason the case crashed on the ORG version; I got a segmentation fault after the solver converged (fields are not written, and it converged in 247 iterations while COM required 379).

I'm using docker image, @philipcardiff  is there some possibility that I bumped into something you already resolved in the development version?

**Comment by iBatistic** [comment]
Since the `fieldCoordinateSystemTransform` function object is not consistent across versions, I have added `transformStressToCylindrical` function object. Also, in the `sample` file face should be replaced with `lineFace` for the ORG version, so I added the corresponding `sed` command in `solids4FoamScripts.sh`. Now the case works on all versions, producing the same results.

p.s. we don't need to use `functions` and `functions.openfoam` files. The following works on all versions:
```
functions
{
    transformStressToCylindrical
    {
        type        transformStressToCylindrical;

        origin      (0 0 0);
        axis        (0 0 1);
    }
}
```

**Comment by philipcardiff** [comment]
> Since the `fieldCoordinateSystemTransform` function object is not consistent across versions, I have added `transformStressToCylindrical` function object. Also, in the `sample` file face should be replaced with `lineFace` for the ORG version, so I added the corresponding `sed` command in `solids4FoamScripts.sh`. Now the case works on all versions, producing the same results.
> 
> p.s. we don't need to use `functions` and `functions.openfoam` files. The following works on all versions:
> 
> ```
> functions
> {
>     transformStressToCylindrical
>     {
>         type        transformStressToCylindrical;
> 
>         origin      (0 0 0);
>         axis        (0 0 1);
>     }
> }
> ```

Thanks @iBatistic. This looks great. I will merge now.

Are you saying that `functions.openfoam` are no longer generally needed? Or just for this case?

**Comment by iBatistic** [comment]
> Are you saying that `functions.openfoam` are no longer generally needed? Or just for this case?

I tried all versions and they work if  `functions{  ... }` syntax is used.

**Comment by philipcardiff** [comment]
This tutorial is now on the website: https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/multiMaterial/layeredPipe.html

**Comment by philipcardiff** [comment]
> > Are you saying that `functions.openfoam` are no longer generally needed? Or just for this case?
> 
> I tried all versions and they work if `functions{ ... }` syntax is used.

Nice. In that case, we can remove the `functions.openfoam` files, checking each one as we go.

**Pull request merged**
