### PR TITLE
Added flat ended rigid indenter contact case

### PR DESCRIPTION
**Pull request by iBatistic**

### CODE REVIEW

**Comment by philipcardiff** [comment]
Thanks again @iBatistic: the tutorials guide on the website is really starting to fill out! :)

I will let the build checks finish and then it looks like it is ready to be merged and added to the website.

**Comment by philipcardiff** [comment]
It looks like I need to make a few edits to the equations (e.g. $ to $$) for GitHub pages to display them correctly.

**Comment by philipcardiff** [comment]
Actually, it seemed to be the alignment of the `$$` signs; it seems that they shouldn't have space before them for out-of-line equations. Hopefully, it is now fixed at https://github.com/solids4foam/solids4foam.github.io/commit/cdca4b152bc52af0b0c9475333e5ffa01f94875b.

Also, I cleaned up the whitespace.

**Comment by philipcardiff** [comment]
Hmnn the fix did not work... the equations are still displayed as inline. Let me try adding a newline

**Comment by philipcardiff** [comment]
@iBatistic : actually, now that I look at the equations again. I notice that equations 2 and 3 are the same and equation 3 is not a function of x (I guess it should be): can you check this?

Possibly, we can merge these two equations?

**Comment by iBatistic** [comment]
Thanks for noticing this; I made mistake, the last equation should look like:

Selection_120

u_z(x) = d + \frac{2(1-\nu^2)F}{\pi E} \text{ ln} \left[ \frac{x}{b} + \sqrt{\frac{x^2}{b^2}-1} \: \:  \right] \qquad \text{for } |x| \geq b.

where $$d$$ is prescribed indenter displacement from equation above.

Do you know, if is it possible to visualise the markdown file to see how they will look once added to the site?

**Comment by philipcardiff** [comment]
> Thanks for noticing this; I made mistake, the last equation should look like:
> 
> Selection_120
> 
> u_z(x) = d + \frac{2(1-\nu^2)F}{\pi E} \text{ ln} \left[ \frac{x}{b} + \sqrt{\frac{x^2}{b^2}-1} : : \right] \qquad \text{for } |x| \geq b.
> 
> where d is prescribed indenter displacement from equation above.

So is this equation a generalization of equation 2? i.e. does this also describe the indenter displacement/depth? If so, we could give just this equation. Also, what is `b`?

**Comment by iBatistic** [comment]
$b$ is the contact half-width and should be replaced with $a$ because I'm using the symbol $a$ for contact half-width; again my mistake! sorry!

This equation describes the boundary displacement of the contact surface outside the contact zone; (that is why i have condition |x|> b). Inside the contact zone displacement is uniform (and the same as prescribed on the indenter). The indenter is rigid, and that is why displacement within the contact zone is uniform and we don't have x coordinate in the first equation. 

I'm not using the second equation in tutorial; however i was planing to do so and add additional graph with contact surface displacement;  i will do this soon i figure out how to properly plot analytical solution solely using gnuplot

**Comment by philipcardiff** [comment]
Finally fixed!

It turns out that using `|` inline makes GitHub pages think it is a separator in a table. So I needed to remove them.

It would probably be useful to figure out how to install a local version of the website to quickly test if the markdowns are converted correctly to html.

**Comment by iBatistic** [comment]
> Finally fixed!

Thanks @philipcardiff!

> It turns out that using | inline makes GitHub pages think it is a separator in a table. So I needed to remove them.

Good to know!

> It would probably be useful to figure out how to install a local version of the website to quickly test if the markdowns are converted correctly to html.

I'll try to find a solution to this.

**Comment by iBatistic** [comment]
I tried [docker-github-pages](https://github.com/Starefossen/docker-github-pages) and [pages-gem](https://github.com/github/pages-gem).  [docker-github-pages](https://github.com/Starefossen/docker-github-pages)  is a deprecated docker image; according to this [response](https://github.com/Starefossen/docker-github-pages/issues/74), [pages-gem](https://github.com/github/pages-gem) should be the right alternative. Anyway neither of those two work for me

**Pull request merged**
