### PR TITLE
solids4foam-v2.1

### PR DESCRIPTION
**Pull request by philipcardiff**
This pull request will mark v2.1. Please feel free to add comments below and any minor changes you think should be included. In particular, any issues to be resolved or other pull requests to be finalised.

To do:
- [x] Add a MarkDown tutorial for the new CHT+FSI functionality.
- [x] Fix FSI in parallel problem for OF.com
- [x] Fix HronTurek case
- [x] Check https://github.com/solids4foam/solids4foam/pull/34 and merge, and update the website as needed.
- [x] Add other MarkDown tutorials (and to the website)
- [x] Merge 3dTube and 3dTubeRobin (use soft links to Allrun for different behaviour)
- [x] Move CHT + FSI to its own parent directory
- [x] Add thermo-FSI tutorial => hotTJunction
- [x] Revert thermalCavity CHT tutorial back to thermal online
- [x] Ensure Allwmake and Alltest pass for FE41, OF9, OF2012
- [x] Ensure Allwmake and Alltest pass for OF2312 and add actions
- [ ] Perform this merge request and create a v2.1 release
- [ ] Update the website installation page with v2.1 and v2.1 version compatibilities
- [ ] Update the website with the release notes for v2.1

After v2.1, we can consider larger (breaking...) changes for v3.0, e.g. new Foundation modular approach, new mechanical law design, etc.

Pinging recent contributors :D @cloner0110 @iBatistic @denMaier

### CODE REVIEW

**Comment by iBatistic** [comment]
Already working on some markdown files for tutorial cases and the code for the issue #90 :)

**Comment by cloner0110** [comment]
@philipcardiff I tried to fix HronTurek, but the issue is quite a bit weird; here is what I've found so far :

1- The case is almost the same as the one we have in Solids4Foam V1, except for some minor BC changes, which I do not think have caused the problem,
2- I tried different mechanical models different from `neoHookean`; all of the ones I tried diverged too but in other time steps.

I will post more updates on this.

**Comment by philipcardiff** [comment]
> @philipcardiff I tried to fix HronTurek, but the issue is quite a bit weird; here is what I've found so far :
> 
> 1- The case is almost the same as the one we have in Solids4Foam V1, except for some minor BC changes, which I do not think have caused the problem, 2- I tried different mechanical models different from `neoHookean`; all of the ones I tried diverged too but in other time steps.
> 
> I will post more updates on this.

Thanks @cloner0110; I suspect that the reason for the case failing is due to some change in the code for the solid models or the solid boundary conditions. One idea is to try to see if a previous commit (e.g. from 6 months ago) works, and from there, we can start to figure out what changes may have broken the case. You can also search for any mentions of HronTurek in commit messages.

**Comment by cloner0110** [comment]
> > @philipcardiff I tried to fix HronTurek, but the issue is quite a bit weird; here is what I've found so far :
> > 1- The case is almost the same as the one we have in Solids4Foam V1, except for some minor BC changes, which I do not think have caused the problem, 2- I tried different mechanical models different from `neoHookean`; all of the ones I tried diverged too but in other time steps.
> > I will post more updates on this.
> 
> Thanks @cloner0110; I suspect that the reason for the case failing is due to some change in the code for the solid models or the solid boundary conditions. One idea is to try to see if a previous commit (e.g. from 6 months ago) works, and from there, we can start to figure out what changes may have broken the case. You can also search for any mentions of HronTurek in commit messages.

Sure, this seems to be a good plan. At first, I thought by changing some models we would identify the source of the problem, apparently, it's not possible that way.

**Comment by cloner0110** [comment]
Hi @philipcardiff, I looked into HronTurek. The case has a problem in the main branch, but it is ok in the development branch; it has been mentioned https://github.com/solids4foam/solids4foam/issues/84#issue-1908720763 that the case is buggy in the dev branch as well, but I couldn't find any problem in the development branch. So we can close it as complete now.

**Comment by philipcardiff** [comment]
> Hi @philipcardiff, I looked into HronTurek. The case has a problem in the main branch, but it is ok in the development branch; it has been mentioned [#84 (comment)](https://github.com/solids4foam/solids4foam/issues/84#issue-1908720763) that the case is buggy in the dev branch as well, but I couldn't find any problem in the development branch. So we can close it as complete now.

Excellent, thanks for this!

**Comment by iBatistic** [comment]
Hi @philipcardiff, here is the list of `functionObjects` covered in tutorials:

- [x] cantileverAnalyticalSolution
- [x]  contactPatchTestAnalyticalSolution
- [x] curvedCantileverAnalyticalSolution
- [x] hotCylinderAnalyticalSolution
- [x] plateHoleAnalyticalSolution
- [x] fsiConvergenceData
- [ ] hydrostaticPressure
- [ ] principalStresses
- [x] solidDisplacements
- [x] solidForces
- [x] solidForcesDisplacements
- [ ] solidKineticEnergy
- [x] solidPointDisplacement
- [ ] solidPointDisplacementAlongLine
- [x] solidPointStress
- [ ] solidPointTemperature
- [ ] solidPotentialEnergy
- [x] solidStresses
- [ ] solidTorque
- [ ] solidTractions
- [ ] stressTriaxiality

The tut case where each applies is documented in the `src/solids4FoamModels/functionObjects/README.md`

Maybe we should think about incorporating some function objects, in existing tutorial cases.

I started working on the readme file for `beamsPlatesShells` cases. I was thinking of making 1 README for all cases, this agrees with your idea of ​​merging.

**Comment by philipcardiff** [comment]
This list is very helpful. I forgot about the functionsObject README file; I will add this to the website at https://www.solids4foam.com/documentation (assuming it is OK with you). Yep, it would no the too difficult to incorporate additional function objects into tutorial cases.

One README for beamsPlatesShells is a good idea; in fact, feel free to remove all cases except for `transientSimplySupportSquarePlate` as I think this one shows the most general functionality.

**Comment by iBatistic** [comment]
> This list is very helpful. I forgot about the functionsObject README file; I will add this to the website at https://www.solids4foam.com/documentation (assuming it is OK with you).

Of course!

>  Yep, it would not be too difficult to incorporate additional function objects into tutorial cases.

I'll put it on my list :)

> One README for beamsPlatesShells is a good idea; feel free to remove all cases except for transientSimplySupportSquarePlate, as I think this one shows the most general functionality.

Sure, I understand

**Comment by philipcardiff** [comment]
The function objects README is now live: https://www.solids4foam.com/documentation/function-objects.html

**Pull request merged**
