### PR TITLE
Documentation draft for solids4foamScripts.sh bash script

### PR DESCRIPTION
**Pull request by iBatistic**

### CODE REVIEW

**Comment by philipcardiff** [comment]
Hi @iBatistic, this is great.

I actually did not think about placing these README files directly in solids4foam (as opposed to only on the website), but of course, that makes perfect sense (keep the documentation with the code/cases).

I will merge this and create the appropriate links on the website.

**Comment by iBatistic** [comment]
> I actually did not think about placing these README files directly in solids4foam (as opposed to only on the website), but of course, that makes perfect sense (keep the documentation with the code/cases).

Oh, I hadn't thought of that. I forgot that we have solids4foam.github.io repo. Please feel free to put the file where you think is better. 

I was unsure of the best approach to write this, so please let me know if you have any suggestions.

p.s. I did not documented `removeEmptyDirs`, `runApplication` and `runParallel` functions. I will add also description for these in the next PR

**Comment by philipcardiff** [comment]
This is definitely the correct location for this README; it makes way more sense to keep the documentation with the code. This means that users can refer directly to READMEs in the solids4foam repo, without the need to visit the website.
Also, it is good for versioning, as the solids4foam repo will track any changes to these READMEs along with the code changes (assuming we keep these up-to-date).

I think a medium-term goal is to:
- add a README for all tutorials and link them on the website (or remove a tutorial if it not have "add value", i.e demonstrate something useful or interesting or some feature)
- add a README for all utilities
- add a README for the solver
- add a README for the scripts (mostly done!)
- add a README for most of the main classes in src libraries

Once we get to that point, then we just need to maintain the README files to match any code/case changes.

**Comment by philipcardiff** [comment]
This is now live on the website: https://www.solids4foam.com/documentation/scripts.html

**Comment by iBatistic** [comment]
@philipcardiff  just a quick question; you plan to add README per utility or one README with the description of all utilities?

I was thinking of doing utilities when I'm done with the scripts...

**Comment by philipcardiff** [comment]
> @philipcardiff just a quick question; you plan to add README per utility or one README with the description of all utilities?
> 
> I was thinking of doing utilities when I'm done with the scripts...

I am not sure. Both are fine (from the website perspective but also from the repository perspective). Since there are only a small number of utilities, maybe it is easier to have just one for now (and we can split it later, if needed), but I am easy.

**Pull request merged**
