### PR TITLE
Added contact patch test tutorial

### PR DESCRIPTION
**Pull request by iBatistic**

### CODE REVIEW

**Comment by philipcardiff** [comment]
Thanks, Ivan.

I will make the changes compatible with OF-9 and OF-v2012 and then merge them.

**Comment by iBatistic** [comment]
Sorry for this; I forgot to check the case with other versions

**Comment by philipcardiff** [comment]
> Sorry for this; I forgot to check the case with other versions

No problem; I am doing it now.

**Comment by philipcardiff** [comment]
All tests should pass now with the latest commits. I will make the merge when the tests are done.

**Comment by philipcardiff** [comment]
I added this to the website: see https://github.com/solids4foam/solids4foam.github.io/commit/ea4f9465749223352920674da98abb39bbe297a7 and https://www.solids4foam.com/tutorials/more-tutorials/solid-mechanics/linearElasticity/contactPatchTest.html.

By the way, the website is now accessible at www.solids4foam.com. Thanks @scottlevie97

**Comment by iBatistic** [comment]
Great, thanks @philipcardiff!

Glad that the page is also on .com domain.

**Pull request merged**
