### PR TITLE
modified flexibleDamBreak Tutorial

### PR DESCRIPTION
**Pull request by cloner0110**
Hi @philipcardiff, I modified flexibleDamBreak and also wrote a markdown for the problem description. The results look okay to me since we have a coarse mesh; maybe later, we can go for alpha-based mesh refinement or even a finer mesh to achieve better results. 

Please tell me your thoughts.

### CODE REVIEW

**Comment by philipcardiff** [comment]
> Hi @philipcardiff, I modified flexibleDamBreak and also wrote a markdown for the problem description. The results look okay to me since we have a coarse mesh; maybe later, we can go for alpha-based mesh refinement or even a finer mesh to achieve better results.
> 
> Please tell me your thoughts.

This looks great @cloner0110! I will take a look at it tomorrow.
@iBatistic: feel free to make suggestions, as you have a lot of experience creating markdowns.

**Comment by cloner0110** [comment]
> > Hi @philipcardiff, I modified flexibleDamBreak and also wrote a markdown for the problem description. The results look okay to me since we have a coarse mesh; maybe later, we can go for alpha-based mesh refinement or even a finer mesh to achieve better results.
> > Please tell me your thoughts.
> 
> This looks great @cloner0110! I will take a look at it tomorrow. @iBatistic: feel free to make suggestions, as you have a lot of experience creating markdowns.


Ok, thanks. @philipcardiff 

I used @iBatistic 's markdown for his recent tutorial. :))

**Comment by iBatistic** [comment]
Nice work  @cloner0110 :)
I noted that you are using `$variable$` notation; use `$$variable$$` everywhere to have a valid render on the web page. I'm using the Typora app, which renders a markdown file most similar to the one on the website.

**Comment by cloner0110** [comment]
> Nice work @cloner0110 :) I noted that you are using `$variable$` notation; use `$$variable$$` everywhere to have a valid render on the web page. I'm using the Typora app, which renders a markdown file most similar to the one on the website.

Thanks, @iBatistic; it is now updated.

**Comment by philipcardiff** [comment]
@cloner0110, I made a few edits to the case:

- Minor edits to the README.md descriptions
- Changed the `solidModel` to a nonlinear geometry model and changed the mechanical law to `neoHookeanElastic` as per the case description in Meduri et al.
- Changed the solid density to 2700 kg/m^3 as in Meduri et al.
- Corrected "top-right" to "top-left" for the deflection monitor point in the README.md (the point is correct but it is misdescribed in the README.md)

The first peak is closer to the Meduri et al. result, but the subsequent oscillations are slightly different; this is fine for the tutorial. I suspect that mesh and time-step errors are the reasons for the difference (I added a note in the README.md).

It is now online at https://www.solids4foam.com/tutorials/more-tutorials/fluid-solid-interaction/flexibleDamBreak.html.

Feel free to propose edits if you see any issues. Thanks again!

**Comment by cloner0110** [comment]
> @cloner0110, I made a few edits to the case:
Thanks @philipcardiff. 

> * Changed the `solidModel` to a nonlinear geometry model and changed the mechanical law to `neoHookeanElastic` as per the case description in Meduri et al.

I also tested `neoHookean`; in my case, the initial peak was lower than that of Meduri et al., but it seems okay now.
> * Changed the solid density to 2700 kg/m^3 as in Meduri et al.
> * Corrected "top-right" to "top-left" for the deflection monitor point in the README.md (the point is correct but it is misdescribed in the README.md)

Oops!
> The first peak is closer to the Meduri et al. result, but the subsequent oscillations are slightly different; this is fine for the tutorial. I suspect that mesh and time-step errors are the reasons for the difference (I added a note in the README.md).
> 
> It is now online at https://www.solids4foam.com/tutorials/more-tutorials/fluid-solid-interaction/flexibleDamBreak.html.

Thanks for the comments, Philip.

**Pull request merged**
