### PR TITLE
fixed problem with poroMechLaw when used with a stress state dependen effStressMechLaw

### PR DESCRIPTION
**Pull request by denMaier**
renamed sigmaEff in mechLaw to deltaSigma,
added sigmaEff to poroMechlaw, and initialize it once at the start of the calculation from sigma and p

When using poroMechLaw with MohrCoulomb effective stress law, the effective stress should be calculated first, since the Mohr-Coulomb  Model depends on the current effective stress state! (It is mean effective pressure tr(sigmaEff) dependent)
Hence, the effective stress is calculated the first time it is needed as sigma+pI and then just saved for later use (next time step).

Since sigmaEff is most fittingly placed within poroMechLaw, I added it there.
I renamed the stress field in mechanicalLaw to deltaSigma, which represents the change of sigma from initial state.
This field is not nesseccarily needed, but since it's used to calculate the material residual in MohrCoulomb, I figured just renaming it is the least invasive option. It is lazyly evaluated anyways, only appearing when MohrCoulomb materialLaw is used.

### CODE REVIEW

**Comment by philipcardiff** [comment]
Thanks for fixing this @denMaier!

Since deltaSigma is only used by linearElasticMohrCoulombPlastic, I moved it there. Can you double-check that it does not break anything for you? It should then be ready to merge.

By the way, if you are interested, feel free to create concise README.md files for any of the poroelasticity tutorials, e.g. it can be placed at https://solids4foam.github.io/tutorials/more-tutorials/solid-mechanics.

**Comment by denMaier** [comment]
Thanks for looking over my changes @philipcardiff . 

In the new commit, I added a sanity check for sigma0 to be initialized non-zero. It doesn't really make much sense to use it without an initial stress field. It is going to output only a warning tough, in case someone really wants to use it that way.

From my point of view, it can be merged, all my tests succeeded. 

I will try to make time to add suitably test cases to the site you mentioned!

**Comment by philipcardiff** [comment]
> Thanks for looking over my changes @philipcardiff .
> 
> In the new commit, I added a sanity check for sigma0 to be initialized non-zero. It doesn't really make much sense to use it without an initial stress field. It is going to output only a warning tough, in case someone really wants to use it that way.
> 
> From my point of view, it can be merged, all my tests succeeded.
> 
> I will try to make time to add suitably test cases to the site you mentioned!

Thanks Denis.

Why does it not make sense for sigma0 to be zero? Excuse me for my ignorance!
For example, does it not make sense to use Mohr-Coulomb where the loading comes purely from boundary conditions as opposed to initial stresses?

**Comment by denMaier** [comment]
> 

In Mohr-Coulomb, the yield-stress has a constant part c and a mean-stress dependent part tan(phi)*1/3*tr(sigma). The constant part is usually really small and so any kind of shear will instantly lead to plastic flow. 
I guess you could construct a case, where you compress isotropically before applying shear (which you could do in a preceeding linear elastic case) or use a high cohesion c (which would make the stress dependent part insignificant around tr(sigma)=0), but I think it is more likely that somebody just forgot (or didn't know about) sigma0.

**Comment by philipcardiff** [comment]
> In Mohr-Coulomb, the yield-stress has a constant part c and a mean-stress dependent part tan(phi)_1/3_tr(sigma). The constant part is usually really small and so any kind of shear will instantly lead to plastic flow.
> I guess you could construct a case, where you compress isotropically before applying shear (which you could do in a preceeding linear elastic case) or use a high cohesion c (which would make the stress dependent part insignificant around tr(sigma)=0), but I think it is more likely that somebody just forgot (or didn't know about) sigma0.

Ah I see; thanks for clarifying!

**Pull request merged**
